/**
 * Registre des icônes du site.
 *
 * Deux jeux, tous deux libres et gratuits :
 *  - Lucide (licence ISC) pour les concepts, actions et objets ;
 *  - Simple Icons (CC0) pour les logos de marques, langages et produits.
 *
 * Un nom court unique est utilisé partout — sidebar, barre de navigation et
 * composants Vue. Les icônes Lucide gardent leur nom d'origine ; les logos
 * sont préfixés `brand-`.
 *
 * La liste `LUCIDE` est le sous-ensemble réellement embarqué : elle se
 * régénère à partir des sources avec `npm run icons:sync`, et la feuille de
 * style `icons.generated.css` est reconstruite au démarrage de VitePress.
 */

/** Logos de marques : nom court → identifiant Simple Icons. */
export const BRANDS = {
  'brand-javascript': 'javascript',
  'brand-python': 'python',
  'brand-rust': 'rust',
  'brand-ruby': 'ruby',
  'brand-c': 'c',
  'brand-django': 'django',
  'brand-linux': 'linux',
  'brand-bash': 'gnubash',
  'brand-ansible': 'ansible',
  'brand-windows': 'windows',
  'brand-powershell': 'powershell',
  'brand-cisco': 'cisco',
  'brand-vmware': 'vmware',
  'brand-splunk': 'splunk',
  'brand-snort': 'snort',
  'brand-elastic': 'elastic',
  'brand-elasticsearch': 'elasticsearch',
  'brand-logstash': 'logstash',
  'brand-kibana': 'kibana',
  'brand-burpsuite': 'burpsuite',
  'brand-metasploit': 'metasploit',
  'brand-wireshark': 'wireshark',
  'brand-tor': 'torproject',
  'brand-github': 'github',
}

/** Icônes Lucide embarquées — généré, voir `npm run icons:sync`. */
export const LUCIDE = [
  'activity',
  'align-left',
  'ambulance',
  'anchor',
  'antenna',
  'app-window',
  'archive',
  'arrow-left-right',
  'award',
  'badge-check',
  'bandage',
  'bell-ring',
  'binary',
  'binoculars',
  'biohazard',
  'blocks',
  'bomb',
  'book-a',
  'book-lock',
  'book-marked',
  'book-open',
  'book-open-check',
  'book-open-text',
  'book-type',
  'bookmark',
  'bot',
  'box',
  'boxes',
  'braces',
  'brain',
  'brick-wall',
  'briefcase',
  'bug',
  'bug-play',
  'building-2',
  'cable',
  'calendar',
  'calendar-clock',
  'car-front',
  'castle',
  'chart-line',
  'check-check',
  'chevrons-right',
  'circle-check-big',
  'circle-help',
  'circle-slash',
  'clipboard-check',
  'clipboard-list',
  'clipboard-pen',
  'clock',
  'cloud',
  'cloud-download',
  'code',
  'code-xml',
  'cog',
  'columns-2',
  'columns-3',
  'combine',
  'command',
  'compass',
  'component',
  'construction',
  'contact',
  'copy',
  'copy-plus',
  'cpu',
  'credit-card',
  'crosshair',
  'database',
  'database-backup',
  'database-zap',
  'door-closed',
  'door-open',
  'download',
  'drafting-compass',
  'drama',
  'droplet',
  'earth',
  'equal',
  'ethernet-port',
  'eye',
  'feather',
  'file-badge-2',
  'file-chart-column',
  'file-code',
  'file-input',
  'file-key',
  'file-lock',
  'file-lock-2',
  'file-output',
  'file-plus',
  'file-search',
  'file-text',
  'file-up',
  'file-warning',
  'filter',
  'fingerprint',
  'flag',
  'flame',
  'flame-kindling',
  'flask-conical',
  'focus',
  'folder-cog',
  'folder-git-2',
  'folder-lock',
  'folder-open',
  'folder-search',
  'folder-symlink',
  'folder-tree',
  'forward',
  'gamepad-2',
  'gauge',
  'gavel',
  'gem',
  'git-branch',
  'git-merge',
  'git-pull-request',
  'github',
  'globe',
  'globe-lock',
  'graduation-cap',
  'grid',
  'hard-drive',
  'hard-drive-download',
  'hard-hat',
  'hash',
  'heart-pulse',
  'history',
  'home',
  'house',
  'id-card',
  'image-off',
  'key',
  'key-round',
  'key-square',
  'keyboard',
  'landmark',
  'laptop',
  'layers',
  'layers-2',
  'layers-3',
  'layout-dashboard',
  'library',
  'library-big',
  'life-buoy',
  'lightbulb',
  'link',
  'list',
  'list-checks',
  'list-tree',
  'lock',
  'lock-keyhole',
  'lock-open',
  'mail',
  'mail-warning',
  'medal',
  'memory-stick',
  'message-square',
  'microscope',
  'milestone',
  'monitor-check',
  'monitor-cog',
  'monitor-dot',
  'monitor-play',
  'moon',
  'network',
  'newspaper',
  'package',
  'package-open',
  'package-x',
  'panel-left-close',
  'panel-left-open',
  'panel-top',
  'panels-top-left',
  'parentheses',
  'play',
  'plug',
  'plug-zap',
  'presentation',
  'puzzle',
  'radar',
  'radio-tower',
  'rectangle-ellipsis',
  'refresh-cw',
  'regex',
  'repeat',
  'rocket',
  'route',
  'router',
  'ruler',
  'save',
  'scale',
  'scale-3d',
  'scan',
  'scan-eye',
  'scan-search',
  'scroll-text',
  'search',
  'search-code',
  'server',
  'server-cog',
  'server-crash',
  'settings-2',
  'shapes',
  'share-2',
  'shield',
  'shield-alert',
  'shield-ban',
  'shield-check',
  'shield-half',
  'shield-off',
  'shield-plus',
  'shield-user',
  'shield-x',
  'shuffle',
  'sigma',
  'signal',
  'signature',
  'signpost',
  'signpost-big',
  'siren',
  'skull',
  'smartphone',
  'sparkles',
  'spline',
  'split',
  'sprout',
  'square-asterisk',
  'square-code',
  'square-function',
  'square-play',
  'square-terminal',
  'stamp',
  'stethoscope',
  'swords',
  'table-2',
  'table-properties',
  'tags',
  'target',
  'terminal',
  'thumbs-up',
  'toggle-left',
  'toggle-right',
  'toy-brick',
  'trees',
  'trending-up',
  'triangle-alert',
  'unlock-keyhole',
  'usb',
  'user-check',
  'user-cog',
  'user-round-cog',
  'users',
  'users-round',
  'vault',
  'venetian-mask',
  'volume-2',
  'wand-sparkles',
  'waves',
  'waypoints',
  'webhook',
  'wifi',
  'workflow',
  'wrench',
  'zap',
]

/** Tous les noms connus, pour la validation. */
export const ICON_NAMES = new Set([...LUCIDE, ...Object.keys(BRANDS)])
